### ISSUE TITLE
Clarity development best practices 

### ISSUE THREAD

**Issue by agraebe** [stacks-network/docs#1194]
Developers often try to understand best practices (or techniques) to solve common goals. It would be great to collect and document them all

cc @lgalabru

**Comment by dcsan** [comment]
agreed. the main docs are pretty thin and google also doesn't come up with a lot, but there are various repos scattered around.

eg megapont put their contracts out which is cool
https://github.com/Megapont/megapont-ape-club-contracts

is there a stacks wiki? 

Would be great to add something like a wiki/faq bot to the discord that is capturing things people share. I made something like that a long time ago, capturing users FAQs to a github wiki. stuff in chat is lost to the sands of time...
https://dc.rik.ai/projects/gitterbot

**Comment by friedger** [comment]
I am happy to help, but don't understand from this issue how :-)

Post on https://source-of-clarity.com have some content that could go here.
