### ISSUE TITLE
Tokens: designing ownership

### ISSUE THREAD

**Issue by lgalabru** [stacks-network/docs#1248]
Following up on https://github.com/blockstack/docs/issues/1249
We should make clear in our documentation that when it comes to token design, they are in charge of designing the rules:
- who can mint
- who can burn
- who can transfer

With a big focus on the fact that `ft-transfer?` and `nft-transfer?` do not include logic like `sender == tx-sender`.

**Comment by LNow** [comment]
It would be great to have few clear examples of different types of ownership that we can build. For example:
* **Full ownership** - similar to STX ownership. Once token is minted or transferred to user, only this user can transfer or burn it.
* **Time based ownership** - user have full control over his tokens up to block X, and after that contract owner or someone else can take it over without user permission.
* **Shared/delegated ownership** - one user owns tokens but can designate another user or list of users who can act on his behalf.
