### ISSUE TITLE
Add example for multisig transfers using STX-on-BTC

### ISSUE THREAD

**Issue by pgray-hiro** [stacks-network/docs#1256]
Add an example to the documentation that demonstrates the [STX-on-BTC method](https://github.com/stacksgov/sips/blob/main/sips/sip-007/sip-007-stacking-consensus.md#stx-operations-on-bitcoin) described in SIP-007.

Requested by @whoabuddy in Discord.

**Comment by whoabuddy** [comment]
I can help with some of what I learned through trial and error - it's quite the process, but after a bunch of test runs we got it working and I documented the process. 😄 

This week will be hectic with the MiamiCoin launch but let's touch base again once things calm down!

**Comment by pgray-hiro** [comment]
If you could send me your notes and the working code I can write it up for the site. Let me know after MiamiCoin settles down.

**Comment by jhammond2012** [comment]
Hi @whoabuddy and @pgray-hiro :) 

Whoabuddy, I just wanted to follow up on this to see if you could share your notes on this. Thanks!

**Comment by jhammond2012** [comment]
Hey, @whoabuddy wanted to ping you on this again if you're still interested.

**Comment by whoabuddy** [comment]
Is this still something that we want in the main documentation, or should I just add it to the original repo?
