### ISSUE TITLE
Remove regtest references from docs

### ISSUE THREAD

**Issue by agraebe** [stacks-network/docs#1269]
https://github.com/blockstack/docs/search?q=regtest

cc @pgray-hiro - should we replicate this issue for the Hiro docs too?

**Comment by jhammond2012** [comment]
Hi @agraebe I am working on resolving this issue. In [this file](https://github.com/blockstack/docs/blob/864ccc42f3e065398ab593e2bd220d7a8e2d6dc9/src/pages/references/stacks-node-configuration/index.md#krypton) it mentions 'regtest' inside of the Krypton section. Seems that this is directly tied to the regtest. My question is, should we just remove this whole Krypton section as well?
