### ISSUE TITLE
running a testnet node specifies xenon

### ISSUE THREAD

**Issue by radicleart** [stacks-network/docs#1275]
Hey - in https://docs.stacks.co/understand-stacks/running-testnet-node

the command 

```docker run -d --rm \
  --name stacks-blockchain \
  -v $(pwd)/persistent-data/stacks-blockchain/testnet:/root/stacks-node/data \
  -p 20443:20443 \
  -p 20444:20444 \
  blockstack/stacks-blockchain \
/bin/stacks-node xenon
```

fails silently. I believe it should specify `testnet` rather than `xenon` ?

**Comment by criadoperez** [comment]
Thanks @radicleart for reporting this.
Yes, you are correct, it should be `testnet` instead of `xenon`.  I verified it works ok with that change. Documentation is being corrected.
