### ISSUE TITLE
Improve developer docs regarding nonces

### ISSUE THREAD

**Issue by larrysalibra** [stacks-network/docs#1299]
The developer documentation on nonce is a bit sparse and developers coming from a bitcoin-only background like me might need a bit of extra hand holding to understand them.

<img width="697" alt="Screen Shot 2022-03-03 at 20 50 11" src="https://user-images.githubusercontent.com/597182/156568534-f9fd5f16-3d46-42e3-ad21-22e5bf03e72c.png">

After reading this and some other comments on github, I made the mistake of assuming that if I broadcast a "wrong" transaction I could replace it by broadcasting one with a higher nonce. This confusion was because I received an error message saying that a transaction with that nonce was already in the mempool when I tried adjusting some parameters of a transaction and broadcasting it.  Seeing this, I thought "oh, i'll just try the next nonce then" and saw that the transaction successfully was broadcasted. It never confirmed of course.

It would be helpful to give concrete examples and clarify that "starting at 0 increment for every transaction" means that a given transaction will only be processed and confirmed by the network if and only confirm if it's nonce is the value of the mostly confirmed transaction plus 1.

Examples with sponsored transactions which need two nonce values would also be very helpful as well.

The comment in the above documentation screenshot about UTXOs is also adds the confusion: my understanding is that Stacks 2.0 is account based and not UTXO based.

**Comment by criadoperez** [comment]
@wileyj are your referring to the google doc of the pending transfers or is there another one I'm not aware of?

If its that one its already published on the docs:

https://docs.stacks.co/faq/overview#what-is-nonce 

Of course, improvements are always welcome :-)

**Comment by criadoperez** [comment]
Closing issue, as this was added to the docs.
