### ISSUE TITLE
"Edit this page on Github" link failing

### ISSUE THREAD

**Issue by criadoperez** [stacks-network/docs#1303]
The link "Edit this page on github" displayed at the bottom right of most pages is failing. A few examples are on these pages:

* https://docs.stacks.co/write-smart-contracts/overview
* https://docs.stacks.co/build-apps/references/gaia

On the first example the link redirects to:  
https://github.com/stacks-network/docs/edit/master/src/pages/en/write-smart-contracts/overview/index.md
and it should be:  
https://github.com/stacks-network/docs/edit/master/src/pages/en/write-smart-contracts/overview.md

On the second example it redirects to:  
https://github.com/stacks-network/docs/edit/master/src/pages/en/build-apps/references/gaia/index.md
When it should be:  
https://github.com/stacks-network/docs/edit/master/src/pages/en/build-apps/references/gaia.md

**Comment by jhammond2012** [comment]
Fixed with PR #1307
