### ISSUE TITLE
incorrect 404 page

### ISSUE THREAD

**Issue by criadoperez** [stacks-network/docs#1314]
When you get a 404 error in any language it doesn't display the expected page.

Expected behavior:
If you go to https://docs.stacks.co/es/page-that-doesnt-exist
the page in /src/pages/es/404.md should load

If you go to https://docs.stacks.co/en/page-that-doesnt-exist
the page in /src/pages/en/404.md should load

**Comment by wileyj** [comment]
#1328

**Comment by criadoperez** [comment]
Fixed on https://github.com/stacks-network/docs/pull/1332
