### ISSUE TITLE
Missing reference/language-function page

### ISSUE THREAD

**Issue by wileyj** [stacks-network/docs#1318]
https://github.com/stacks-network/docs/pull/1309

seems to have broken the link: https://docs.stacks.co/references/language-functions

**Comment by wileyj** [comment]
update: seems to have moved to  https://docs.stacks.co/write-smart-contracts/language-functions

can we add some routes or something to handle bookmarks etc, or is that something we'll need to address at the proxy layer?

**Comment by jhammond2012** [comment]
@wileyj does at redirect work for this?

**Comment by wileyj** [comment]
should be fine, yeah

**Comment by criadoperez** [comment]
Fixed on #1319
