### ISSUE TITLE
New docs page/section for "help, my tx is pending" etc

### ISSUE THREAD

**Issue by wileyj** [stacks-network/docs#1347]
Based on the mempool congestion recently, we've started a (private-ish) doc to store some details on what to do if a user tx is pending for longer than expected. 

Some things we're tracking is "how to check  your nonce is correct" and "is the tx fee too low for current network conditions?"

**Comment by Hero-Gamer** [comment]
Here I am JW!

**Comment by wileyj** [comment]
@whoabuddy for visibility as well. @Hero-Gamer please tag anyone else you want in this issue

**Comment by whoabuddy** [comment]
Thanks! Tagging @LNow too as he's been big on supporting users

**Comment by Hero-Gamer** [comment]
@cargocultscience
