### ISSUE TITLE
A way to pull discord messages into the project or discord issue

### ISSUE THREAD

**Issue by jhammond2012** [stacks-network/docs#1351]
It seems that a commonplace for people to post issues is the Discord server. If we could somehow pull these common requests into a formatted list, I feel we could learn a lot from this.

For example, if it is common for someone to ask about common functions, for example, it would be clear that we aren't doing a great job at showcasing that info inside the docs. Maybe setting up a canny board for this? I am not sure of the correct solution here but wanted to open this for discussion.

**Comment by criadoperez** [comment]
Related to issue #1419
