### ISSUE TITLE
Translation Price Research

### ISSUE THREAD

**Issue by ImTheCodeFarmer** [stacks-network/docs#1352]
Research various services for the initial translation. 
---
- price
- services included
- timeline

**Comment by jhammond2012** [comment]
https://translationreport.com/top-10-translation-services

**Comment by jhammond2012** [comment]
Pricing in this industry is very misleading. No matter the listed price, unless you are doing some un-fathomable amount of volume or you are willing to use computer-generated translations then you will end up paying around $0.016 per word. Currently, the docs contain $33,000+- words which come out to be $5,277.64 per language. 

I have reached out to the global channels in discord in hopes that I can get some more community support for translation.

**Comment by criadoperez** [comment]
Thanks @jhammond2012  for the research and calculating the estimate cost per language.
I also reached out the community to see if we can get some help.
We should however close [this issue](https://github.com/stacks-network/docs/issues/1337) first so translations can actually get published as they come in.
