### ISSUE TITLE
Vercel run duplicated

### ISSUE THREAD

**Issue by criadoperez** [stacks-network/docs#1354]
We are currently running 2 Vercel runs in parallel:

* blockstacks-docs
* docs

We should move all the functionality to docs.

**Comment by jhammond2012** [comment]
@criadoperez what are the next steps on this? Maybe @wileyj can help here?

**Comment by criadoperez** [comment]
Maybe the easiest option would be for someone with permissions to the `blockstacks-docs` to transfer the project to `docs` (of the team "stacks-team").
That way we don't have to reprogram the functionality of `docs`.
Anybody with permissions for this?
![image](https://user-images.githubusercontent.com/8580472/165715714-6010a5ce-e989-4725-b7c0-5702f15e28b1.png)

**Comment by diwakergupta** [comment]
> Maybe the easiest option would be for someone with permissions to the `blockstacks-docs` to transfer the project to `docs` (of the team "stacks-team"). That way we don't have to reprogram the functionality of `docs`. Anybody with permissions for this?

We can also check on Hiro's end (cc/ @CharlieC3 ) -- though I would recommend just creating a new Vercel project that is under Foundation / community governance for this repo.

**Comment by criadoperez** [comment]
> I would recommend just creating a new Vercel project that is under Foundation / community governance for this repo.

That's exactly what we did! :+1:  Now we just need to transfer the project from one user to the other.

**Comment by CharlieC3** [comment]
@criadoperez If you already created your own Vercel project for this repo, wouldn't it be better if we just deleted the corresponding project Hiro owns instead of transferring it?

**Comment by criadoperez** [comment]
I don't mind. Whatever is easier... I would have thought that transferring would be easier but I may be wrong. The main thing is that our Vercel account should be able to deploy on docs.stacks.co

Our Vercel project in publishing on the following URLs:
docs-stacks-team.vercel.app
docs-one-sigma.vercel.app
docs-git-master-stacks-team.vercel.app

blockstacks-docs is publishing on the following URLs:
blockstack-docs.vercel.app
docs.stacks.co
blockstack-docs-blockstack.vercel.app
blockstack-docs-git-master-blockstack.vercel.app
docs.blockstack.org
docs-staging.blockstack.org

If you delete `blockstack-docs`, will it then allow me to enable `docs`to deploy on docs.stacks.co or I'll need some sort of permissions for that?

**Comment by CharlieC3** [comment]
@criadoperez ah so it seems the two projects aren't exact copies due to the domain differences. Also, it doesn't seem like I'm able to transfer the project over unless we're a part of the stacks-team. I've requested access.

**Comment by criadoperez** [comment]
I accepted the request.

**Comment by CharlieC3** [comment]
Transferred over! Let me know if it looks good on your end.

**Comment by criadoperez** [comment]
Thanks @CharlieC3 ! That seems to have worked.
For the record, we know have only one Vercel project called `stacks-docs` that replaces both `docs` and `blockstacks-docs'
