### ISSUE TITLE
Old testnet status / link

### ISSUE THREAD

**Issue by obycode** [stacks-network/docs#1361]
docs.stacks.co has this outdated status bar and link at the bottom. This is no longer useful and should be removed.

![image](https://user-images.githubusercontent.com/1473715/165667036-a437aaf4-b00e-4210-9218-57eaefb20a91.png)

**Comment by jhammond2012** [comment]
Hi @obycode! Would you be interested in fixing this and opening a PR?

**Comment by criadoperez** [comment]
I don't see the status bar on docs.stacks.co
Could you please send a full screenshot or a URL of where your see it?

![image](https://user-images.githubusercontent.com/8580472/165712491-2af856e2-0fca-4a70-9c84-1559ddfd20aa.png)

**Comment by obycode** [comment]
Ok, it was definitely there yesterday (I can't be imagining it because I took that screenshot 😆), but I'm not seeing it now. Did someone already remove it?

**Comment by obycode** [comment]
Good idea. Yes, that could make sense.

**Comment by obycode** [comment]
Yup, it is still there:
![image](https://user-images.githubusercontent.com/1473715/165760671-ef4f28df-27be-412d-8c01-579a8fa95f0f.png)
