### ISSUE TITLE
List of network modes and stacks-node binary

### ISSUE THREAD

**Issue by criadoperez** [stacks-network/docs#1366]
@wileyj, could you please confirm this [list](https://docs.stacks.co/nodes-and-miners/stacks-node-configuration#mode) of modes is no longer valid?

Also, isn't the section of [stacks-node binary](https://docs.stacks.co/nodes-and-miners/stacks-node-configuration#usage) obsolete and completely replaced by the docker option?

**Comment by wileyj** [comment]
copying from a call with @criadoperez :
start the binary with each option (separately):
- testnet
- mainnet

if both options bring up the correct chain, the noble gas names can be removed from the docs.
