### ISSUE TITLE
Running a node docs need to be updated

### ISSUE THREAD

**Issue by criadoperez** [stacks-network/docs#1454]
**Describe the issue**
Current pages:
https://docs.stacks.co/docs/nodes-and-miners/running-mainnet-node
and
https://docs.stacks.co/docs/nodes-and-miners/running-testnet-node

need to be updated or replaced by this method:

https://github.com/stacks-network/stacks-blockchain-docker

**Comment by friedger** [comment]
It would be nice to still have documentation about the details if we don't use the docker setup. However, the first point of contact for node runners should be indeed more like stacks-blockchain-docker

**Comment by criadoperez** [comment]
Current method published in the docs also uses docker... so I don't see any benefit of keeping the "older" way of doing it.
If we do however, keep two separate tutorials to run a node, we should add clear instructions on when we recommend using one tutorial or another. So users don't get confused. 
Can you tell me on which cases you would recommend using the older method instead of the new one?
