### ISSUE TITLE
Algolia search not working

### ISSUE THREAD

**Issue by criadoperez** [stacks-network/docs#1473]
**Describe the issue**
Algolia search is not working due to a wrong Github secrets config.

Search works fine when run locally, but on github its not reading the github secret correctly.

**Comment by criadoperez** [comment]
Opened Algolia support ticket

**Comment by wileyj** [comment]
any updates? there have been questions about this specifically

**Comment by criadoperez** [comment]
Algolia replied but didn't provide a clear solution.

**Comment by criadoperez** [comment]
Algolia confirms the API key is public so it can be disclosed and removed from Github secrets
