### ISSUE TITLE
Wrong signature algorithm referenced on accounts page

### ISSUE THREAD

**Issue by hstove** [stacks-network/docs#1475]
URL of the page to change: https://github.com/stacks-network/docs/blame/master/docs/understand-stacks/accounts.md#L14

---

The line "The public-key signature system used for Stacks 2.0 accounts is [Ed25519]" is, I am pretty sure, incorrect. The curve used is secp256k1. Please feel free to double check this - not exactly my area of expertise.

**Comment by friedger** [comment]
ed25519 is only used in context of the VRF (for the proof: https://github.com/stacks-network/stacks-blockchain/blob/26bfd5fcdc1f25106288f18ced05290b569f6abb/stacks-common/src/util/vrf.rs#L276)

secp256k1 for everything else, e.g. https://github.com/stacks-network/stacks-blockchain/blob/26bfd5fcdc1f25106288f18ced05290b569f6abb/src/chainstate/stacks/auth.rs#L52

**Comment by criadoperez** [comment]
Thank you @hstove for raising this issue and @friedger for verifying and providing the links.
