### ISSUE TITLE
[Edit docs] un-escape quotes in examples

### ISSUE THREAD

**Issue by obycode** [stacks-network/docs#1491]
URL of the page to change: https://docs.stacks.co/docs/write-smart-contracts/clarity-language/language-functions
---

![image](https://user-images.githubusercontent.com/1473715/180453174-da182f58-6bd4-4608-8813-1fae2bbbc679.png)

As seen in the screenshot above, the examples are showing up with the quotes escaped (`\"` instead of just `"`).

**Comment by criadoperez** [comment]
Thanks @obycode for pointing this out.

**Comment by obycode** [comment]
This issue is back.

**Comment by obycode** [comment]
Confirming this is currently fixed.
