### ISSUE TITLE
Page content list incomplete

### ISSUE THREAD

**Issue by friedger** [stacks-network/docs#1571]
**Describe the issue**
The list of sections (right side bar) of the page "https://docs.stacks.co/docs/build-apps/references/bns" is missing `BNS and DID Standards`.

**Screenshots**
![image](https://user-images.githubusercontent.com/1449049/215353316-865721b5-5f9b-4095-8176-b8ab855244fa.png)

**Comment by wileyj** [comment]
<img width="1660" alt="Screenshot 2023-02-17 at 17 36 13" src="https://user-images.githubusercontent.com/2847772/219824695-17c53b37-4cf0-4259-ba14-a9c848137388.png">


confirmed. @kenrogers can you take a look here?

**Comment by friedger** [comment]
This issue is still important to me

**Comment by kenrogers** [comment]
Will take a look at this tomorrow and get it fixed.

**Comment by kenrogers** [comment]
This has been fixed with https://github.com/stacks-network/docs/commit/836e2815ebec55b754b947f7ee4f1d8de326e44d
