### ISSUE TITLE
Missing content

### ISSUE THREAD

**Issue by markmhx** [stacks-network/docs#1572]
I can find these pages via search, but they don't load:

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/28991/217586121-797c114a-5235-4065-a3cc-d1ca2ba1f20e.png">

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/28991/217586154-be8206f4-8c3e-4a5a-bf54-1042f3286a50.png">

**Comment by wileyj** [comment]
This could be a result of an older search index after a large refresh was pushed to master. 
searching now for "bns" and "zone-file" look fine - can you try it gain and let me know it it's still a problem?

**Comment by friedger** [comment]
Search results link to https://docs.stacks.co/docs/clarity/noteworthy-contracts/bns-contract
Please open a new issue if you find missing content
