### ISSUE TITLE
Add Clarity 2 functions and keywords references

### ISSUE THREAD

**Issue by hugocaillard** [stacks-network/docs#1575]
[clarity/language-functions](https://docs.stacks.co/docs/clarity/language-functions) - [clarity/language-keywords](https://docs.stacks.co/docs/clarity/language-keywords)
---

Developers can write Clarity 2 since a few weeks, the doc should reflect that.
These page could include a Clarity version selector

**Comment by wileyj** [comment]
Good idea - would you be willing to PR the change here? not sure how soon we'll be able to address this on our end

**Comment by hugocaillard** [comment]
@wileyj Sure, you can assign it I'm taking care of it today
