### ISSUE TITLE
Permissions for Latest whitepaper of GAIA (May 2022) do not allow public reading

### ISSUE THREAD

**Issue by mgrand** [stacks-network/docs#1581]
On [https://docs.stacks.co/docs/gaia](https://docs.stacks.co/docs/gaia) there is a link to the Latest whitepaper of GAIA (May 2022) at [https://dev1-gaia-hub.s3.amazonaws.com/GAIA_Whitepaper.pdf](https://dev1-gaia-hub.s3.amazonaws.com/GAIA_Whitepaper.pdf). When I click on the link, I see
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>54Q2F5220KEGZM4Y</RequestId>
<HostId>iJqtkSi2EYzfZW2mAFm4VBDDqD/wMxo5kFj+qJGITRqiZVgU8f8DXwdQ2/0BZpbQdDjykAsrzcI=</HostId>
</Error>
```

**Comment by kenrogers** [comment]
Broken link removed
