### ISSUE TITLE
[Add docs] Chain agnostic docs

### ISSUE THREAD

**Issue by friedger** [stacks-network/docs#1591]
---
title: Chain Agnostic Definitions
description: Using chain agnostic standards for Stacks assets and protocols
---

### Stacks Token ([CAIP-20](https://namespaces.chainagnostic.org/stacks/caip20))
The native Stacks token on mainnet is referenced as
`stacks:1/slip44:5757`

### Stacks Accounts ([CAIP-10](https://namespaces.chainagnostic.org/stacks/caip10))
Accounts are references by their STX address, for example for mainnet as 
`stacks:1/SP2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKNRV9EJ7`

### SIP9 and SIP10 tokens ([CAIP-19](https://github.com/ChainAgnostic/namespaces/pull/68/files))
Similarily, tokens are referenced using their smart contract: 
`stacks:1/sip10:SP3DX3H4FEYZJZ586MFBS25ZW3HZDMEW92260R2PR.Wrapped-Bitcoin` or 
`stacks:1/sip9:SP3D6PV2ACBPEKYJTCMH7HEN02KP87QSP8KTEH335.megapont-space-agency/4`

### Sign-in with Stacks ([CAIP-122](https://namespaces.chainagnostic.org/stacks/caip122))
The signature type is defined as `stacks:secp256k1`

### Wallet Connect v2
The following methods are defined: `stacks_contractCall`, `stacks_stxTransfer`, `stacks_signMessage`, and `stacks_contractDeploy`.
Xverse mobile wallet has implemented support for Wallet Connect v2

**Comment by kenrogers** [comment]
Closing this as the links lead to 404 pages. However, feel free to comment if you think this is still relevant and we can explore more.
