### ISSUE TITLE
[Edit docs] Small link fix for mining page

### ISSUE THREAD

**Issue by ecorona9** [stacks-network/docs#1593]
URL of the page to change: https://docs.stacks.co/docs/stacks-academy/mining
---
Explain here what you would like to change.

The clickable link called `miner on mainnet` as below

https://docs.stacks.co/docs/nodes-and-miners/miner-testnet

should instead take you to

https://docs.stacks.co/docs/nodes-and-miners/miner-mainnet

**Comment by kenrogers** [comment]
Mining link fixed
