### ISSUE TITLE
Error (Access Denied) for whitepapers -> proof of transfer 

### ISSUE THREAD

**Issue by neilmehta31** [stacks-network/docs#1594]
**Describe the issue**
The link [Proof Of Transfer](https://assets.website-files.com/5fcf9ac604d37418aa70a5ab/60072dbb32d416d6b3806935_5f1596b12bcc0800f3dcadcd_pox.pdf) shows error on opening with the following error message.

**Screenshots**
![image](https://github.com/stacks-network/docs/assets/59043233/e4070bc3-d236-4ecb-b5f1-197c388fcbbc)

**Comment by edgarkhanzadian** [comment]
This issue is still reproducible

**Comment by neilmehta31** [comment]
@criadoperez can you have a look at this? The file seems deleted/moved from the bucket
