### ISSUE TITLE
[Add docs] Add design/brand guidelines

### ISSUE THREAD

**Issue by friedger** [stacks-network/docs#1596]
---
title: Design and Brand Guidelines
description: 
---

## Logo
The Stacks logo is hosted at ... and should be used always like ....

## Name
Stacks is used to describe the Stacks ecosystem, the token is described as STX or Stacks token....

**Comment by kenrogers** [comment]
Brand guide and kit live on Figma, which I think makes sense for brand guidelines. Post here with relevant links: https://stacks.org/brand-refresh

This page also includes a link to communication guidelines. I don't know that it makes sense to include this info in technical docs.
