### ISSUE TITLE
[Edit docs] Change references to Hiro Wallet to Leather Wallet

### ISSUE THREAD

**Issue by AshtonStephens** [stacks-network/docs#1598]
URL of the page to change: https://docs.stacks.co/docs/tutorials/hello-stacks

---

This page references `Hiro Wallet` but the wallet has been rebranded to `Leather Wallet`.  This is the only page I've read so I bet there are other occurrences as well.

IMO it's probably sufficient to find and replace instances of `Hiro wallet` with `Leather wallet` in the docs and update the first instance of `Hiro wallet` in each page with `Leather wallet (formerly Hiro wallet)` to avoid confusion.

**Comment by AshtonStephens** [comment]
Also I suppose this bit under [Wallet Setup](https://docs.stacks.co/docs/tutorials/hello-stacks#wallet-setup) is technically wrong because the wallet app is owned by Trust Machines:

> ... visit Hiro's [wallet page](https://wallet.hiro.so/) and install it. ...

**Comment by kenrogers** [comment]
Going through and catching up on old docs issues. Sorry for the delay on this, got this fixed.
