### ISSUE TITLE
[Edit docs]

### ISSUE THREAD

**Issue by xor777** [stacks-network/docs#1600]
URL of the page to change: https://docs.stacks.co/docs/stacks-academy/whitepapers
---

Link to the Proof-of-transfer whitepaper is broken https://assets.website-files.com/5fcf9ac604d37418aa70a5ab/60072dbb32d416d6b3806935_5f1596b12bcc0800f3dcadcd_pox.pdf

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>HW57RJX8Z3DHCN9S</RequestId>
<HostId>zloZM8YI4RdPRzJUfIQdznH3bIODff4hRzaeljZiEisQlS7nQodkI/iDnONYPvWM7gxPtd20gmc8W89G+E9emA==</HostId>
</Error>

**Comment by kenrogers** [comment]
Removed the PoX link in favor of the new Stacks Nakamoto whitepaper link.
