### ISSUE TITLE
[Edit docs] Update outdated info on segwit support

### ISSUE THREAD

**Issue by diwakergupta** [stacks-network/docs#1603]
There are several references in docs (e.g. [here](https://docs.stacks.co/docs/stacks-academy/stacking#stacking-delegation-flow)) that say segwit addresses are not support (e.g. to receive stacking yield). 

However, as of Stacks 2.1, both segwit and taproot addresses are supported. Relevant issues:

https://github.com/stacks-network/stacks-core/issues/2586
https://github.com/stacks-network/stacks-core/issues/2905

**Comment by kenrogers** [comment]
Thanks for flagging @diwakergupta this has been fixed with this commit: https://github.com/stacks-network/docs/commit/0657ad90ce9a55181aebb6f6bfe9fa85df29aba6

Let me know if you notice anything else!
