### ISSUE TITLE
Bad formatting in Clarity function examples

### ISSUE THREAD

**Issue by csgui** [stacks-network/docs#1604]
Clarity functions examples has a bad formatting.

For instance, function `var-set`:

After changes:
`(define-data-var cursor int 6)(var-get cursor) ;; Returns 6(var-set cursor (+ (var-get cursor) 1)) ;; Returns true(var-get cursor) ;; Returns 7`

Previously was:
```
(define-data-var cursor int 6)
(var-get cursor) ;; Returns 6

(var-set cursor (+ (var-get cursor) 1)) ;; Returns true
(var-get cursor) ;; Returns 7
```

Is it possible to have a better formatting, like previously, for function examples? Thanks!

**Comment by kenrogers** [comment]
Fixed by https://github.com/stacks-network/docs/pull/1605
