### ISSUE TITLE
[Edit docs] Missing `!` on some functions

### ISSUE THREAD

**Issue by obycode** [stacks-network/docs#1606]
URL of the page to change: https://docs.stacks.co/clarity/functions
---
Explain here what you would like to change.

When the subtitles are matching the function name, they should include the `!` when appropriate. For example, https://docs.stacks.co/clarity/functions#try should be labeled `try!`, but the `!` is missing.

**Comment by obycode** [comment]
After posting that link, I also noticed that the `#try` fragment identifier is not working to jump to that location on the page.

**Comment by kenrogers** [comment]
Missing `!` added and id link working, thanks Brice!
