### ISSUE TITLE
Add Planbetter as a cycle-84-available pool

### ISSUE THREAD

**Issue by planbetterHQ** [stacks-network/docs#1623]
Text to show:

`[Planbetter](https://planbetter.org/)`

https://github.com/stacks-network/docs/blob/9f784cf941f26754387b40d54ae7d949305b0a61/nakamoto-upgrade/nakamoto-rollout-plan/nakamoto-for-stackers.md?plain=1#L13

**Comment by cuevasm** [comment]
This was done immediately, closing as no longer relevant
