### ISSUE TITLE
Security Vulnerability in Stacks-network/docs

### ISSUE THREAD

**Issue by nvk0x** [stacks-network/docs#1628]
Hi,

I am an bugbounty hunter and found two high severity security vulnerability in this repository.
Do you have bugbounty program or where can i report about it ?

Thanks & Regards
naveen

**Comment by wileyj** [comment]
We have no bug bounty for marketing sites, only the blockchain itself.

**Comment by wileyj** [comment]
you're welcome to PR changes to fix anything you've found though.

**Comment by nvk0x** [comment]
Hey, I am not gonna submit vulnerability reports for free
